version: "3"
services:
  apuestas-api:
    build: .
    environment:
      DBServer: host.docker.internal
      DBPort: "5432"
      DBUser: "postgres"
      Password: "moki-moki24"
      Database: "Lotto"
    ports:
      - "8080:80"